sudo: required
services:
    - docker

before_install:
    - docker build -t johnsontrevor55/docker-react -f Dockerfile.dev .

script:
    - docker run johnsontrevor/docker-react npm run test -- --coverage
